Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # virtualboxのGUI設定を有効化
    vb.gui = true
    vb.memory = "4096"

    vb.customize [
      "modifyvm", :id,
      # フルスクリーンモード用
      "--vram", "256",
      # クリップボード共有
      "--clipboard", "bidirectional",
      # ドラッグアンドドロップ
      "--draganddrop", "bidirectional",
      "--cpus", "4",
      "--ioapic", "on" # I/O APICを有効化
    ]
  end

  # デスクトップ環境に必要なものをVM内にinstall
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade

    apt-get install -y \
      ubuntu-desktop \
      apt-transport-https \
      ca-certificates \
      software-properties-common

    reboot
  SHELL
end
